# Generated by Django 6.0.3 on 2026-03-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tematica',
            field=models.CharField(choices=[('AUTOMATA', 'Archivo del Autómata'), ('LAB', 'Laboratorio Dimensional'), ('NUBES', 'Ciudad en las Nubes')], default='NUBES', max_length=10),
        ),
    ]
